spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://postgres-db:5432/usersystem
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500

management.endpoints.web.exposure.include=health