spring.application.name=email-service
server.port=8082

spring.datasource.url=jdbc:postgresql://postgres-db:5432/usersystem
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.cloud.consul.host=consul
spring.cloud.consul.port=8500

management.endpoints.web.exposure.include=health

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourmail
spring.mail.password=yourpassword

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
